Функциональность «Лента событий». 3 SP
darsavellis/java-filmorate pull request #10
Opened 2024-08-11 08:14 UTC by IvanHamitsev

💡 Ветка для реализации задачи должна называться add-feed.

Описание задачи
Добавить возможность просмотра последних событий на платформе — добавление в друзья, удаление из друзей, лайки и отзывы, которые оставили друзья пользователя. Для этого вам понадобится создать таблицу для хранения информации о пользователе — что он лайкнул, кого добавил в друзья, написал ли отзыв.

API
GET /users/{id}/feed

Возвращает ленту событий пользователя.

Пример JSON-объекта с которым работает эндпоинт
[
    {
        "timestamp": 123344556,
        "userId": 123,
        "eventType": "LIKE", // одно из значениий LIKE, REVIEW или FRIEND
			  "operation": "REMOVE", // одно из значениий REMOVE, ADD, UPDATE
        "eventId": 1234, //primary key
        "entityId": 1234   // идентификатор сущности, с которой произошло событие
    }
]

2024-08-12 13:41 UTC, Evgen1aGerasimenko approved these changes

2024-08-13 17:26 UTC, darsavellis requested changes
Так, я не увидел кнопку finish your review)
Не нажимал ее

2024-08-13 17:26 UTC, darsavelidze commented on src/main/java/ru/yandex/practicum/filmorate/dal/impl/JdbcReviewRepository.java
> +    private static final String FIND_REVIEW_QUERY = "SELECT * FROM reviews WHERE id = :review_id";
Над классом стоит FieldDefaults(level = AccessLevel.PRIVATE), можно убирать все private

2024-08-13 17:26 UTC, darsavelidze commented on src/main/java/ru/yandex/practicum/filmorate/dal/impl/JdbcReviewRepository.java
> +        SqlParameterSource parameters = new MapSqlParameterSource()
В методе updateReview есть почти такая же мапа, которая имеет на один ключ больше. Можно вынести в отдельный метод и возвращать в обоих местах, лишняя id не помешает коду, зато не будет дублирования

2024-08-13 17:26 UTC, darsavelidze commented on src/main/java/ru/yandex/practicum/filmorate/dal/impl/JdbcReviewRepository.java
> +        long id = generatedKeyHolder.getKeyAs(Long.class);
Тут по моему IDEA ворчит, возвращаемое значение может быть null, а мы его в long кидаем. Лучше получить Long, а потом проверить на != null

2024-08-13 17:26 UTC, darsavelidze commented on src/main/java/ru/yandex/practicum/filmorate/dal/impl/JdbcReviewRepository.java
> +            Long score = jdbc.queryForObject(COUNT_REVIEW_SCORE, new MapSqlParameterSource("review_id",
Мало параметров, лаконичнее Map.of()

2024-08-13 17:26 UTC, darsavelidze commented on src/main/java/ru/yandex/practicum/filmorate/dal/ReviewRepository.java
> +    void setLikeReview(long reviewId, long userId, boolean ifPositive);
тут наверно isPositive

2024-08-13 17:26 UTC, darsavelidze commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/BaseFilmService.java
> +        Film res = getFilmById(filmId);
По моему так нельзя называть переменные по их правилам. Кстати, а по какой причине решил разбить на две строки? Более читаемо?

2024-08-13 17:26 UTC, darsavelidze commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/BaseReviewService.java
> +    private static final String REVIEW_ID_NOT_FOUND = "Review ID=%s not found";
Тут тоже лишние private

2024-08-13 17:26 UTC, darsavelidze commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/BaseReviewService.java
> +@Slf4j
Не используется

2024-08-13 17:26 UTC, darsavellis commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    @PutMapping("/{id}/like/{userId}")
Мне на ревью говорили прочитать про правила написание адресов, типа не userId, а user-id
Но я не знаю верно ли это или нет, я после этого везде писал через -

2024-08-14 08:27 UTC, IvanHamitsev commented on src/main/java/ru/yandex/practicum/filmorate/dal/impl/JdbcReviewRepository.java
> +        SqlParameterSource parameters = new MapSqlParameterSource()
Они всё же разные, я бы не стал делать лишнее действие ради вынесения кода в отдельный метод, кода всего два места, где он бы использовался.

2024-08-14 08:29 UTC, IvanHamitsev commented on src/main/java/ru/yandex/practicum/filmorate/dal/impl/JdbcReviewRepository.java
> +        long id = generatedKeyHolder.getKeyAs(Long.class);
Да. Сделал это в соседней ветке add-reviews. При слиянии возьмём код оттуда.

2024-08-14 08:30 UTC, IvanHamitsev commented on src/main/java/ru/yandex/practicum/filmorate/dal/impl/JdbcReviewRepository.java
> +            Long score = jdbc.queryForObject(COUNT_REVIEW_SCORE, new MapSqlParameterSource("review_id",
Согласен. Сделал в ветке add-reviews

2024-08-14 08:33 UTC, IvanHamitsev commented on src/main/java/ru/yandex/practicum/filmorate/dal/ReviewRepository.java
> +    void setLikeReview(long reviewId, long userId, boolean ifPositive);
точно!

2024-08-14 08:37 UTC, IvanHamitsev commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/BaseFilmService.java
> +        Film res = getFilmById(filmId);
Разбил на две строки по тому, что сначала надо сделать editLike, и только потом eventLike. Если сделать наоборот, возможна ситуация, когда событие запишется, а вот editLike завершится провалом.
res - сокращение от слова result, обозначает короткую временную переменную и иногда допускается, как например i в счётчике цикла. Не знаю как у нас, на всякий случай сделал result

2024-08-14 08:43 UTC, IvanHamitsev commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    @PutMapping("/{id}/like/{userId}")
Я это переписал прямо из задания, вот например:
"PUT /reviews/{id}/like/{userId} — пользователь ставит лайк отзыву."
Давай пока оставим так, ревьювер скажет привести к формату правил написания адресов - приведём.

2024-08-14 13:26 UTC, darsavellis approved these changes

2024-08-14 16:06 UTC, merged