Функциональность «Отзывы». 4 SP
darsavellis/java-filmorate pull request #11
Opened 2024-08-11 08:29 UTC by IvanHamitsev

💡 Ветка для реализации задачи должна называться add-reviews.

Описание задачи
В приложении должны появиться отзывы на фильмы. Добавленные отзывы должны иметь рейтинг и несколько дополнительных характеристик.

Характеристики отзыва.

Оценка — полезно/бесполезно.
Тип отзыва — негативный/положительный.
Рейтинг отзыва.

У отзыва имеется рейтинг. При создании отзыва рейтинг равен нулю. Если пользователь оценил отзыв как полезный, это увеличивает его рейтинг на 1. Если как бесполезный, то уменьшает на 1.

Отзывы должны сортироваться по рейтингу полезности.

API
POST /reviews

Добавление нового отзыва.

PUT /reviews

Редактирование уже имеющегося отзыва.

DELETE /reviews/{id}

Удаление уже имеющегося отзыва.

GET /reviews/{id}

Получение отзыва по идентификатору.

GET /reviews?filmId={filmId}&count={count}
Получение всех отзывов по идентификатору фильма, если фильм не указан то все. Если кол-во не указано то 10.

PUT /reviews/{id}/like/{userId} — пользователь ставит лайк отзыву.
PUT /reviews/{id}/dislike/{userId} — пользователь ставит дизлайк отзыву.
DELETE /reviews/{id}/like/{userId} — пользователь удаляет лайк/дизлайк отзыву.
DELETE /reviews/{id}/dislike/{userId} — пользователь удаляет дизлайк отзыву.
Описание JSON-объекта с которым работают эндпоинты
{
    "reviewId": 123,
    "content": "This film is sooo baad.",
    "isPositive": false,
    "userId": 123, // Пользователь
    "filmId": 2, // Фильм
    "useful": 20 // рейтинг полезности 
}

2024-08-12 02:06 UTC, Evgen1aGerasimenko approved these changes

2024-08-13 17:28 UTC, darsavellis requested changes

2024-08-13 17:28 UTC, darsavelidze commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    private final ReviewService reviewService;
Над классом стоит FieldDefaults(level = AccessLevel.PRIVATE)

2024-08-13 17:28 UTC, darsavelidze commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public ResponseEntity<List<Review>> getReviewsByFilmId(@RequestParam(required = false) Optional<Long> filmId,
Кстати idea отмечает Optinal-ы в параметрах, не знаю почему, ощущение, что так делать не надо, но на baeldung такие примеры есть

2024-08-13 17:28 UTC, darsavelidze commented on src/main/java/ru/yandex/practicum/filmorate/dal/impl/JdbcFilmRepository.java
> +    static String DELETE_QUERY = "DELETE FROM films WHERE id = :id";
static final наверно лучше

2024-08-13 17:28 UTC, darsavellis commented on src/main/java/ru/yandex/practicum/filmorate/dal/impl/JdbcReviewRepository.java
> +    private static final String FIND_REVIEW_QUERY = "SELECT * FROM reviews WHERE id = :review_id";
В классе лишние private

2024-08-13 17:28 UTC, darsavellis commented on src/main/java/ru/yandex/practicum/filmorate/dal/impl/JdbcReviewRepository.java
> +                    new MapSqlParameterSource("review_id", reviewId),
Если параметр один, то Map.of("review_id", reviewId) был бы короче (но мб эти штуки MapSqlParameterSource более рекомендуемые, новые интерфейсы содержат только их, например batch, если не ошибаюсь).

2024-08-13 17:28 UTC, darsavellis commented on src/main/java/ru/yandex/practicum/filmorate/dal/impl/JdbcReviewRepository.java
> +            if (Objects.nonNull(score)) {
Можно сразу в Optional засунуть, проверять isPresent(), а потом его же и вернуть не оборачивая

2024-08-13 17:28 UTC, darsavellis commented on src/main/java/ru/yandex/practicum/filmorate/dal/impl/JdbcReviewRepository.java
> +        } catch (EmptyResultDataAccessException e) {
Я бы сделал DataAccessException, он самый верхний для этого метода
```
<T> T queryForObject(String sql, Map<String, ?> paramMap, RowMapper<T> rowMapper) throws DataAccessException;
```

2024-08-13 17:28 UTC, darsavellis commented on src/main/java/ru/yandex/practicum/filmorate/dal/impl/JdbcReviewRepository.java
> +        SqlParameterSource parameters = new MapSqlParameterSource()
Вынес бы в отдельный метод, чтобы его же использовать в create

2024-08-13 17:28 UTC, darsavellis commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    long useful = 0;
Ноль можно не присваивать, по моему он по дефолту будет

2024-08-13 17:28 UTC, darsavellis commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/BaseReviewService.java
> +@Slf4j
Не используется

2024-08-13 17:28 UTC, darsavellis commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/BaseReviewService.java
> +    private static final String REVIEW_ID_NOT_FOUND = "Review ID=%s not found";
В классе лишние private

2024-08-14 07:32 UTC, IvanHamitsev commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    private final ReviewService reviewService;
Всё хотел погуглить, что же это за аннотация, но руки так и не дошли. Конкретно в этом классе он не нужен, почти всё public

2024-08-14 07:35 UTC, IvanHamitsev commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public ResponseEntity<List<Review>> getReviewsByFilmId(@RequestParam(required = false) Optional<Long> filmId,
Да, тоже обратил внимание. Но она не подсказывает толком почему. Я так и не разбирался, оставил. Наверное можно было перейти на просто Long и проверку на null, но разницы не вижу, тогда зачем тратить время..

2024-08-14 07:43 UTC, IvanHamitsev commented on src/main/java/ru/yandex/practicum/filmorate/dal/impl/JdbcReviewRepository.java
> +            if (Objects.nonNull(score)) {
Не прочувствовал профита, приблизительно то же самое вышло.

2024-08-14 07:49 UTC, IvanHamitsev commented on src/main/java/ru/yandex/practicum/filmorate/dal/impl/JdbcReviewRepository.java
> +                    new MapSqlParameterSource("review_id", reviewId),
Думаю нет, без разницы. В стандартных интерфейсах используется MapSqlParameterSource скорее всего для акцентирования внимания. Там нет задачи писать проще и быстрее

2024-08-14 08:03 UTC, IvanHamitsev commented on src/main/java/ru/yandex/practicum/filmorate/dal/impl/JdbcReviewRepository.java
> +        SqlParameterSource parameters = new MapSqlParameterSource()
Не вижу смысла: наша задача писать проще, быстрее, читабельнее. В методе create и update объект SqlParameterSource заполняется разным составом полей, значит просто вынести кусок кода в отдельный метод не выйдет, надо делать какой-то "умный" метод, понимающий какие поля брать. Это дороже по времени разработки, отладки, да и читабельность пострадает. Учитывая, что это нужно всего в двух методах класса - мне кажется так делать не стоит.

2024-08-14 08:04 UTC, IvanHamitsev commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    long useful = 0;
Специально поставил здесь 0 для акцентирования внимания, что ревью по умолчанию имеет рейтинг.

2024-08-14 13:21 UTC, darsavellis approved these changes

2024-08-14 14:29 UTC, merged